name: Python

on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

env:
  PYTHON_VERSION: 3.9

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: abatilo/actions-poetry@v2.1.5
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: poetry install

    - uses: isort/isort-action@master

    - name: Run lint with black
      run: |
        poetry run black --check .

    - name: Lint with flake8
      if: always()
      run: |
        poetry run flake8 --count --statistics

    - name: Lint with mypy
      if: always()
      run: |
        poetry run mypy .

    - name: Run custom style checks
      if: always()
      run: |
        poetry run cicd/custom_style_check.py

  test:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2
    - name: Install dependencies
      run: |
        poetry install
    - name: Run pytest
      run: |
        poetry run pytest -vv
        poetry run pytest -vv > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'created' }}

  build:
    name: Build linkedin_messaging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2
    - name: Run build
      run: |
        poetry build

  test_deploy:
    name: Test Deploy to PyPi
    runs-on: ubuntu-latest
    needs: [lint, test, build]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2

    - name: Run build
      run: |
        poetry build

    - name: Dry run publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_DEPLOY_TOKEN }}
        poetry publish --dry-run

  deploy:
    name: Deploy to PyPi
    runs-on: ubuntu-latest
    needs: [test_deploy]
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2

    - name: Run build
      run: |
        poetry build

    - name: Actual publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_DEPLOY_TOKEN }}
        poetry publish
